### ISSUE TITLE
请问是否可以完善下使用和设置说明

### ISSUE THREAD

**Issue by xyetim** [goshan/werewolf#19]
比如功能页面的地址列表和设置、用户权限等说明
看得有点懵，本人水平有限

**Comment by goshan** [comment]
@xyetim 谢谢你的建议。
目前这个项目一直都是内部适用，并没有公开，所以相关说明文档比较欠缺。我们会陆续补上相应的文档并通知您。

**Comment by goshan** [comment]
@xyetim 

更新了一些文档至 https://github.com/goshan/werewolf/tree/master/documents
请参考。

如果有什么疑问欢迎随时联系。谢谢！

**Comment by xyetim** [comment]
能收到您的回复真是万分喜悦，非常感谢您针对我提出问题作出的完善工作。
看了下代码，估计easy_login要改成账号密码注册、登录的方式验证不同玩家和管理员的鉴别才能减少长久运行出错乱。
我水平有限，空闲看看能不能深入编改吧，有意见会及时提出来的！
   GL！
